"""empty message

Revision ID: 80f1ba345e0d
Revises: 
Create Date: 2022-10-07 10:09:20.371917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80f1ba345e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_path', sa.Column('original_file_name', sa.String(length=50), nullable=False))
    op.add_column('file_path', sa.Column('copies_made', sa.Integer(), nullable=True))
    op.add_column('file_path', sa.Column('edited_file_path', sa.String(length=100), nullable=False))
    op.drop_column('file_path', 'file_name')
    op.drop_column('file_path', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_path', sa.Column('file_path', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('file_path', sa.Column('file_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('file_path', 'edited_file_path')
    op.drop_column('file_path', 'copies_made')
    op.drop_column('file_path', 'original_file_name')
    # ### end Alembic commands ###
